version: "3.9"

services:
  backend:
    build:
      context: .
    container_name: backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000
